company_A_management_system/company_A_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('Company-A/', include('company_A_app.urls')),
    path('E-Procurement/', include('procurement_app.urls')),
    path('Vendor/', include('vendor_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

company_A_management_system/home/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from home.views import (

    HomeView,
    LogoutView,

)

app_name = 'home'

urlpatterns = [

    path('', HomeView, name='home'),
    path('logout/', LogoutView, name='logout'),


]

company_A_management_system/vendor_app/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

app_name = 'vendor_app'

from vendor_app.views import (

    offerView

)

urlpatterns = [

    path('procurement-offers/', offerView, name="offer"),
    # path('Inventory/', InventoryView, name="procurement")

]

company_A_management_system/templates/navbar.html
 
 <!-- Navbar starts here   -->
 <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">
    <a class="navbar-brand" href="#">Company A</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home:home' %}">Home</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:home' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home:home' %}">Registration</a>
      </li>
      {% endif %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'vendor_app:offer' %}">Procurement Offers</a>
      </li>
    </ul>
 </div>
</nav>
<!-- navbar ends here -->