company_A_management_system/company_A_app/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from company_A_app.views import (

    DashboardView,

)

app_name = 'company_A_app'

urlpatterns = [

    path('Dashboard/', DashboardView, name="dashboard"),

]

company_A_management_system/company_A_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('Company-A/', include('company_A_app.urls')),
    path('E-Procurement/', include('procurement_app.urls')),
    path('Vendor/', include('vendor_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

company_A_management_system/home/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from home.views import (

    HomeView,
    LogoutView,

)

app_name = 'home'

urlpatterns = [

    path('', HomeView, name='home'),
    path('logout/', LogoutView, name='logout'),


]

company_A_management_system/procurement_app/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from procurement_app.views import (

    CreateProcurementOfferView,
    OffersForAProductView,
    AcceptingVendorOffer,
    ProcurementOrderView,
    FinalizePaymentView

)

app_name="procurement_app"

urlpatterns = [

    path('Create-A-Procurement-Offer/', CreateProcurementOfferView, name="create_procurement_offer"),
    path('Offers/<str:product_id>', OffersForAProductView, name='particular_product_offers'),
    path('Accept-Offer/<str:proposal_id>/<str:product_id>/', AcceptingVendorOffer, name='accepting_offer'),
    path('Order-View/<str:vendor_unique_code>/', ProcurementOrderView, name="order_view"),
    path('Finalize-Payment/<str:vendor_unique_code>/', FinalizePaymentView, name="payment")

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

company_A_management_system/procurement_app/models.py
from django.db import models
from company_A_app.models import ProfileModel   
from vendor_app.models import proposalModel

from datetime import datetime

# Create your models here.
class ProcurementOfferModel(models.Model):

    product_name = models.CharField(max_length=100)
    product_quantity = models.FloatField()
    product_unit = models.CharField(max_length=100)
    product_price_per_unit = models.FloatField()
    status = models.CharField(max_length=100, default="Pending")
    issue_date = models.DateField(default=datetime.now)
    due_date = models.DateField()
    vendor_unique_code = models.CharField(max_length=100, blank=True)
    company_a_proc_id = models.CharField(max_length=100)


    def __str__(self):
        return self.product_name


def payment_attachment_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/reference_number/<filename>
    return 'payment/{}/{}'.format(instance.vendor_unique_code, filename)


class AcceptedOfferDetailsModel(models.Model):

    due_date = models.DateField()
    vendor_unique_code = models.CharField(max_length=100)
    total_cost = models.FloatField()
    status = models.CharField(max_length=100, default="Ongoing")
    proc_offer = models.ForeignKey(ProcurementOfferModel, on_delete=models.CASCADE)
    vendor = models.ForeignKey(proposalModel, on_delete=models.CASCADE)
    paid_using = models.CharField(max_length=100, blank=True)
    paid_amount = models.CharField(max_length=100, blank=True)
    attachments = models.FileField(upload_to=payment_attachment_path, blank=True)
    # paid_on = models.DateField(blank=True)

    def __str__(self):
        return self.proc_offer.product_name


    

company_A_management_system/procurement_app/forms.py
from django import forms

from procurement_app.models import ProcurementOfferModel


class ProcurementOfferForm(forms.ModelForm):

    class Meta: 
        model = ProcurementOfferModel
        fields = [
            'product_name',
            'product_quantity',
            'product_price_per_unit',

        ]

company_A_management_system/procurement_app/views.py
from django.shortcuts import render

from random import randint

from procurement_app.models import ProcurementOfferModel, AcceptedOfferDetailsModel
from company_A_app.models import CompanyAInventoryModel
from vendor_app.models import proposalModel

from procurement_app.forms import ProcurementOfferForm

from django.http import HttpResponse

from django.template.loader import render_to_string
from django.core.mail import send_mail, EmailMessage
from django.conf import settings




# Create your views here.

def CreateProcurementOfferView(request):

    products = CompanyAInventoryModel.objects.all()

    if 'offer_submission' in request.POST:

        print("Creating a procurement offer")

        incoming_data = {
            'product_name': request.POST['product_name'],
            'product_quantity': request.POST['product_quantity'],
            'product_price_per_unit': request.POST['product_price_per_unit'],
            # 'due_date': request.POST['due_date'],
        }

        print(incoming_data)

        incoming_info = ProcurementOfferForm(incoming_data)

        if incoming_info.is_valid():
            print("valid")

            product_id = CompanyAInventoryModel.objects.get(product_name=request.POST['product_name']).company_a_product_id

            model = ProcurementOfferModel(
                    product_name = request.POST['product_name'],
                    product_quantity = request.POST['product_quantity'],
                    product_price_per_unit=request.POST['product_price_per_unit'],
                    product_unit = request.POST['product_unit'],
                    due_date = request.POST['due_date'],
                    company_a_proc_id=product_id
                )
            model.save()

            # unique_code = randint(10000, 99999)

    proc_offers = ProcurementOfferModel.objects.all()

    context = {
        'products': products,
        'proc_offers': proc_offers
    }

    return render(request, 'procurement_app/create_procurement_offer.html', context)



def OffersForAProductView(request, product_id):
    print("Product ID: ", product_id)

    procurement_offer = ProcurementOfferModel.objects.get(company_a_proc_id=product_id)
    print(procurement_offer.product_name)

    vendor_offer = proposalModel.objects.filter(product_id=product_id)

    context = {

        'procurement_offer': procurement_offer,
        'vendor_offers': vendor_offer

    }

    return render(request, "procurement_app/vendor_offers_for_a_particular_product.html", context)


def AcceptingVendorOffer(request, proposal_id, product_id):

    print("Product ID: ", product_id)

    vendor_offer = proposalModel.objects.get(proposal_id=proposal_id)

    print("Proposal ID: ", proposal_id)

    proc_offer = ProcurementOfferModel.objects.get(company_a_proc_id=product_id)

    unique_code = randint(10000, 99999)

    if ProcurementOfferModel.objects.all().count() == 0:
        

        total_cost = (vendor_offer.vendor_price) * (vendor_offer.vendor_quantity)

        # model = AcceptedOfferModel(
        #     due_date = proc_offer.due_date,
        #     vendor_unique_code = unique_code,
        #     offered_price_per_unit = vendor_offer.vendor_price,
        #     offered_quantity = vendor_offer.vendor_quantity,
        #     total_cost = total_cost,
        #     proc_offer = proc_offer
        # )
        # model.save()

        model = AcceptedOfferDetailsModel(
            due_date = proc_offer.due_date,
            vendor_unique_code = unique_code,
            total_cost = total_cost,
            proc_offer = proc_offer,
            vendor=vendor_offer,
        )
        model.save()

        proc_offer.status = "Accepted"
        proc_offer.vendor_unique_code=unique_code
        proc_offer.save()

        mail_subject = 'Congratulations'
        message = render_to_string('procurement_app/accepted_offer_email.html', {
            'uid': unique_code,
        })
        to_email = vendor_offer.vendor_email
        email = EmailMessage(
                    mail_subject, message, to=[to_email]
        )
        print("The email being sent")
        print("Email will be sent to: ", vendor_offer.vendor_email)
        print(message)
        # email.send()

    else:
        
        current_unique_codes = []
        for i in ProcurementOfferModel.objects.all():
            current_unique_codes.append(i.vendor_unique_code)

        while(unique_code in current_unique_codes):
            unique_code = randint(10000, 99999)

        total_cost = (vendor_offer.vendor_price) * (vendor_offer.vendor_quantity)

        # model = AcceptedOfferModel(
        #     due_date = proc_offer.due_date,
        #     vendor_unique_code = unique_code,
        #     offered_price_per_unit = vendor_offer.vendor_price,
        #     offered_quantity = vendor_offer.vendor_quantity,
        #     total_cost = total_cost,
        #     proc_offer = proc_offer
        # )
        # model.save()

        model = AcceptedOfferDetailsModel(
            due_date = proc_offer.due_date,
            vendor_unique_code = unique_code,
            total_cost = total_cost,
            proc_offer = proc_offer,
            vendor=vendor_offer,
        )
        model.save()

        proc_offer.status = "Accepted"
        proc_offer.vendor_unique_code=unique_code
        proc_offer.save() 

        mail_subject = 'Congratulations'
        message = render_to_string('procurement_app/accepted_offer_email.html', {
            'uid': unique_code,
        })
        to_email = vendor_offer.vendor_email
        email = EmailMessage(
                    mail_subject, message, to=[to_email]
        )
        print("The email being sent")
        print(message)
        # email.send()



    return HttpResponse("Request Accepted")


def ProcurementOrderView(request, vendor_unique_code):

    print("Here: ", vendor_unique_code)

    accepted_offer = AcceptedOfferDetailsModel.objects.get(vendor_unique_code=vendor_unique_code)

    context = {
        'accepted_offer': accepted_offer
    }

    return render(request, 'procurement_app/procurement_order.html', context)

def FinalizePaymentView(request, vendor_unique_code):

    accepted_offer = AcceptedOfferDetailsModel.objects.get(vendor_unique_code=vendor_unique_code)

    if 'payment_submission' in request.POST:

        incoming_data = {
            'payment_method' : request.POST['payment_method']
        }
        print(incoming_data)

        accepted_offer.paid_using = request.POST['payment_method']
        accepted_offer.paid_amount = request.POST['amount']
        accepted_offer.attachments = request.POST.get('attachments', False)
        accepted_offer.paid_on = request.POST['payment_date']
        accepted_offer.status = "Paid"
        accepted_offer.save()

        return HttpResponse("Your payment was successful")



    return render(request, "procurement_app/payment.html")

company_A_management_system/procurement_app/templates/procurement_app/accepted_offer_email.html
Congratulations , your offer has been accepted , please use the code: {{uid}} to track your transaction. 
Thank you.

company_A_management_system/procurement_app/templates/procurement_app/create_procurement_offer.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/home.css' %}">
    <title>Mangement System</title>
  </head>
  <body class="bg-transparant">



    <!-- Navbar starts here   -->
    {% include 'navbar.html' %}
   <!-- navbar ends here -->

<div class="container-fluid">
  <!-- Headline starts here -->

    <div class="circle1"></div>
    <div class="circle2"></div>
    <div class="circle3"></div>
    <div class="circle4"></div>

  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link active" href="{% url 'company_A_app:dashboard' %}">Dashboard</a>
    </li>

    <li class="nav-item">
      <a class="nav-link active" href="">Procurement Offers</a>
    </li>
  </ul>
  <!-- Headline ends here -->
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-3 bg-light" style='opacity:0.9;border-radius:5px;'>

    <form method="POST" class="affix"style="padding:5px;">

        {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputState">Product Name</label>
          <select id="inputState" name="product_name" class="form-control">
            <option selected>Choose...</option>
            {% for i in products %}
            <option>{{i}}</option>
            {% endfor %}
          </select>
          <small>If you don't find a product, please add it to your Inventory first</small>
        </div>
        <div class="form-group col-md-6">
          <label for="product_quantity">Product quantity</label>
          <input type="text" class="form-control" name="product_quantity" value="">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">Product Unit</label>
          <input type="text" name="product_unit" class="form-control" id="inputCity">
        </div>
        <div class="form-group col-md-6">
          <label for="inputState">Product price/unit</label>
          <input type="text" class="form-control" name="product_price_per_unit" value="">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">Due Date</label>
          <input type="date" name="due_date" class="form-control" id="inputCity">
        </div>
      </div>
      <br>
      <button type="submit" name="offer_submission" class="btn btn-primary">Click to add item for vendors</button>

    </form>

  </div>

  <div class="col-sm-7">
        <table class="table">
    <thead>

      <tr>
        <th scope="col">Product ID</th>
        <th scope="col">Product Name</th>
        <th scope="col">Product Quantity</th>
        <th scope="col">Product Unit</th>
        <th scope="col">Price/Unit BDT</th>
        <th scope="col">Issue Date</th>
        <th scope="col">Status</th>
        <th scope="col">-</th>
      </tr>

    </thead>
    <tbody>
      {% for i in proc_offers %}
      <tr>
        <th scope="row">{{i.company_a_proc_id}}</th>
        <td>{{i.product_name}}</td>
        <td>{{i.product_quantity}}</td>
        <td>{{i.product_unit}}</td>
        <td>{{i.product_price_per_unit}}</td>
        <td>{{i.issue_date}}</td>
        {% if i.status == "Pending" %}
        <td>{{i.status}}</td>
        <td>
          <a href="{% url 'procurement_app:particular_product_offers' product_id=i.company_a_proc_id %}">
          <button class="btn btn-success">Click Here</button>
          </a>
        </td>
        {% elif i.status == "Accepted" %}
        <td>{{i.status}}</td>
        <td>
          <a href="{% url 'procurement_app:order_view' vendor_unique_code=i.vendor_unique_code %}">
            <button>
              View Details
            </button>
          </a>
        </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
    </table>
  </div>

  <div class="col-sm-1"></div>
</div>

  <div class="row">


<div class="col-sm-2"></div>
  <div class="col-sm-8 bg-light" style='opacity:0.9'>

    </div>
    <div class="col-sm-2"></div>
  </div>

</div>


<!--
  <a href="{% url 'home:logout' %}">
  <button>Click here to Logout</button>
  </a> -->









<!-- Footer -->
<footer class="page-footer fixed-bottom font-small bg-dark">

<!-- Copyright -->
<div class="footer-copyright text-center py-3 text-light">© 2020 Copyright:
  <a href="#"> company A</a>
</div>
<!-- Copyright -->

</footer>


  </body>
</html>

company_A_management_system/procurement_app/templates/procurement_app/payment.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/home.css' %}">
    <title>Mangement System</title>
  </head>
  <body class="bg-transparant">



    <!-- Navbar starts here   -->
    {% include 'navbar.html' %}
   <!-- navbar ends here -->

<div class="container-fluid">
  <!-- Headline starts here -->

    <div class="circle1"></div>
    <div class="circle2"></div>
    <div class="circle3"></div>
    <div class="circle4"></div>

  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'company_A_app:dashboard' %}">Dashboard</a>
    </li>
  </ul>
  <!-- Headline ends here -->

  <div class="col-sm-3 bg-light" style='opacity:0.9;border-radius:5px;'>

    <form method="POST" class="affix"style="padding:5px;">

        {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputState">Payment Method</label>
          <select id="inputState" name="payment_method" class="form-control">
            <option selected>Choose...</option>
            <option>Cash</option>
            <option>Bank Transfer</option>
            <option>Cheque Payment</option>
            <option>Other</option>
          </select>

        </div>
        <div class="form-group col-md-6">
          <label for="product_quantity">Amount</label>
          <input type="text" class="form-control" name="amount" value="">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-10">
          <label for="inputCity">Please attach the receipt/necessary file for proof</label>
          <input type="file" name="attachments" class="form-control" id="inputCity">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">Paid on</label>
          <input type="date" name="payment_date" class="form-control" id="inputCity">
        </div>
      </div>
      <br>
      <button type="submit" name="payment_submission" class="btn btn-primary">Submit!</button>

    </form>

  </div>




  <!-- Footer -->
  <footer class="page-footer fixed-bottom font-small bg-dark">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-light">© 2020 Copyright:
      <a href="#"> company A</a>
    </div>
    <!-- Copyright -->
    
    </footer>
    
    </body>

</html>
    

company_A_management_system/procurement_app/templates/procurement_app/procurement_order.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/home.css' %}">
    <title>Mangement System</title>
  </head>
  <body class="bg-transparant">



    <!-- Navbar starts here   -->
    {% include 'navbar.html' %}
   <!-- navbar ends here -->

<div class="container-fluid">
  <!-- Headline starts here -->

    <div class="circle1"></div>
    <div class="circle2"></div>
    <div class="circle3"></div>
    <div class="circle4"></div>

  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'company_A_app:dashboard' %}">Dashboard</a>
    </li>
  </ul>
  <!-- Headline ends here -->

  <h3>Accepted Offer for {{accepted_offer.proc_offer.product_name}}</h3>

  <br>
  <p></p>

  <div class="col-sm-9">
    <table class="table">
<thead>
  
  <tr>
    <th scope="col">Vendor Name</th>
    <th scope="col">Vendor Email</th>
    <th scope="col">Offered Price/Unit (BDT)</th>
    <th scope="col">Offered Quantity</th>
    <th scope="col">Additional Notes</th>
    <th scope="col">Due Date</th>
    <th scope="col">Total Cost (BDT)</th>
    <th scope="col">Payment Status</th>
  </tr>
  
</thead>
<tbody>
  <tr>
    <td>{{accepted_offer.vendor.vendor_name}}</td>
    <td>{{accepted_offer.vendor.vendor_email}}</td>
    <td>{{accepted_offer.vendor.vendor_price}}</td>
    <td>{{accepted_offer.vendor.vendor_quantity}}</td>
    <td>{{accepted_offer.vendor.vendor_info}}</td>
    <td>{{accepted_offer.due_date}}</td>
    <td>{{accepted_offer.total_cost}}</td>   
    <td>
      <a href="{% url 'procurement_app:payment' vendor_unique_code=accepted_offer.vendor_unique_code %}">
      <button>
        Click here to finalize payment
      </button>
      </a>
    </td>   
  </tr>
</tbody>
</table>
</div>



  <!-- Footer -->
<footer class="page-footer fixed-bottom font-small bg-dark">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-light">© 2020 Copyright:
      <a href="#"> company A</a>
    </div>
    <!-- Copyright -->
    
    </footer>
    
    </body>

</html>
    

company_A_management_system/procurement_app/templates/procurement_app/vendor_offers_for_a_particular_product.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/home.css' %}">
    <title>Mangement System</title>
  </head>
  <body class="bg-transparant">



    <!-- Navbar starts here   -->
    {% include 'navbar.html' %}
   <!-- navbar ends here -->

<div class="container-fluid">
  <!-- Headline starts here -->

    <div class="circle1"></div>
    <div class="circle2"></div>
    <div class="circle3"></div>
    <div class="circle4"></div>

  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'company_A_app:dashboard' %}">Dashboard</a>
    </li>
  </ul>
  <!-- Headline ends here -->

  <h3>Vendor Offers for {{procurement_offer.product_name}}</h3>

  <br>
  <p></p>

  <div class="col-sm-7">
    <table class="table">
<thead>
  
  <tr>
    <th scope="col">Vendor Name</th>
    <th scope="col">Vendor Email</th>
    <th scope="col">Offered Price</th>
    <th scope="col">Offered Quantity</th>
    <th scope="col">Additional Notes</th>
    <th scope="col">-</th>
  </tr>
  
</thead>
<tbody>
  {% for i in vendor_offers %}
  <tr>
    <td>{{i.vendor_name}}</td>
    <td>{{i.vendor_email}}</td>
    <td>{{i.vendor_price}}</td>
    <td>{{i.vendor_quantity}}</td>
    <td>{{i.vendor_info}}</td>
    <td>
      <a href="{% url 'procurement_app:accepting_offer' proposal_id=i.proposal_id product_id=i.product_id %}">
      <button>Accept</button>
      </a>
    </td>
      
  </tr>
  {% endfor %}
</tbody>
</table>
</div>



  <!-- Footer -->
<footer class="page-footer fixed-bottom font-small bg-dark">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3 text-light">© 2020 Copyright:
      <a href="#"> company A</a>
    </div>
    <!-- Copyright -->
    
    </footer>
    
    </body>

</html>
    