company_A_management_system/company_A_app/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from company_A_app.views import (

    DashboardView,

)

app_name = 'company_A_app'

urlpatterns = [

    path('Dashboard/', DashboardView, name="dashboard"),

]

company_A_management_system/company_A_management_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('Company-A/', include('company_A_app.urls')),
    path('E-Procurement/', include('procurement_app.urls')),
    path('Vendor/', include('vendor_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

company_A_management_system/home/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from home.views import (

    HomeView,
    LogoutView,

)

app_name = 'home'

urlpatterns = [

    path('', HomeView, name='home'),
    path('logout/', LogoutView, name='logout'),


]

company_A_management_system/procurement_app/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from procurement_app.views import (

    CreateProcurementOfferView,
    OffersForAProductView,
    AcceptingVendorOffer,
    ProcurementOrderView,
    FinalizePaymentView

)

app_name="procurement_app"

urlpatterns = [

    path('Create-A-Procurement-Offer/', CreateProcurementOfferView, name="create_procurement_offer"),
    path('Offers/<str:product_id>', OffersForAProductView, name='particular_product_offers'),
    path('Accept-Offer/<str:proposal_id>/<str:product_id>/', AcceptingVendorOffer, name='accepting_offer'),
    path('Order-View/<str:vendor_unique_code>/', ProcurementOrderView, name="order_view"),
    path('Finalize-Payment/<str:vendor_unique_code>/', FinalizePaymentView, name="payment")

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

company_A_management_system/company_A_app/models.py
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class ProfileModel(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    company_email = models.CharField(max_length=250)
    company_role = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.first_name + " " + self.last_name)

class CompanyAInventoryModel(models.Model):
    product_name = models.CharField(max_length=100)
    product_quantity = models.FloatField()
    product_unit = models.CharField(max_length = 50)
    product_price_per_unit = models.FloatField()
    product_added_by = models.ForeignKey(ProfileModel, on_delete=models.CASCADE)
    company_a_product_id = models.IntegerField()

    def __str__(self):
        return self.product_name

company_A_management_system/company_A_app/forms.py
from django import forms
from company_A_app.models import CompanyAInventoryModel, ProfileModel

class CompanyAInventoryForm(forms.ModelForm):

    class Meta:
        model= CompanyAInventoryModel
        fields = [
            'product_name',
            'product_unit',
            'product_quantity',
            'product_price_per_unit'
        ]

company_A_management_system/company_A_app/views.py
from django.shortcuts import render, redirect

from company_A_app.models import CompanyAInventoryModel, ProfileModel

from company_A_app.forms import CompanyAInventoryForm

# Create your views here.


def DashboardView(request):

    profile = ProfileModel.objects.get(user=request.user)

    if 'adding_product' in request.POST:
        print("Am I here")

        incoming_data = {
                'product_name': request.POST['product_name'],
                'product_unit': request.POST['product_unit'],
                'product_quantity': request.POST['product_quantity'],
                'product_price_per_unit': request.POST['product_price_per_unit'],
                # 'product_id': request.POST['product_id']
            }

        print(incoming_data)

        incoming_info = CompanyAInventoryForm(incoming_data)

        if CompanyAInventoryModel.objects.all().count() == 0:

            if incoming_info.is_valid():
                print("First time")
                
                model = CompanyAInventoryModel(
                    product_name = request.POST['product_name'],
                    product_unit = request.POST['product_unit'],
                    product_price_per_unit = request.POST['product_price_per_unit'],
                    product_quantity = request.POST['product_quantity'],
                    product_added_by = profile,
                    company_a_product_id = 1

                )
                model.save()

            else:
                print(incoming_info.errors)

        else:

            current_product_id = CompanyAInventoryModel.objects.all().count() + 1

            if incoming_info.is_valid():
                print("there is history")
                model = CompanyAInventoryModel(
                    product_name = request.POST['product_name'],
                    product_unit = request.POST['product_unit'],
                    product_price_per_unit = request.POST['product_price_per_unit'],
                    product_quantity = request.POST['product_quantity'],
                    product_added_by = profile,
                    company_a_product_id = current_product_id,                    

                )
                model.save()

            else:
                print(incoming_info.errors)


    products = CompanyAInventoryModel.objects.all()

    context = {
        'profile': profile,
        'products': products
    }


    return render(request, "company_A_app/dashboard.html", context)

company_A_management_system/company_A_app/templates/company_A_app/dashboard.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/home.css' %}">
    <title>Mangement System</title>
  </head>
  <body class="bg-transparant">

    <!-- Navbar starts here   -->
    {% include 'navbar.html' %}
   <!-- navbar ends here -->

<div class="container-fluid">
  <!-- Headline starts here -->

    <div class="circle1"></div>
    <div class="circle2"></div>
    <div class="circle3"></div>
    <div class="circle4"></div>

  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'company_A_app:dashboard' %}">Dashboard</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'procurement_app:create_procurement_offer' %}">Procurement Offers</a>
    </li>
  </ul>
  <!-- Headline ends here -->
<div class="row">
  <div class="col-sm-1"></div>
  <div class="col-sm-2">
    <div class="card" style="width: 18rem; height: 20rem; border-radius:10px;">
      <!-- <img src="..." class="card-img-top" alt="..."> -->
      <div class="card-body">
        <h5 class="card-title">Employee Info</h5><hr>
        <p class="card-text">First Name: {{profile.first_name}}</p>
        <p class="card-text">Last Name: {{profile.last_name}}</p><hr>
        <p class="card-text">Email: {{profile.company_email}}</p><hr>
        <p class="card-text">Role: {{profile.company_role}}</p>

      </div>
    </div>

  </div>

  <div class="col-sm-8 bg-light" style="opacity:0.9;border-radius:10px;">
    <form method="POST">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-4">
          <label for="inputState">Product Name</label>
          <input type="text" class="form-control" name="product_name">
        </div>
        <div class="form-group col-md-4">
          <label for="product_quantity">Product quantity</label>
          <input type="text" class="form-control" name="product_quantity" value="">
        </div>
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">Product Unit</label>
          <input type="text" name="product_unit" class="form-control" id="inputCity">
        </div>
        <div class="form-group col-md-6">
          <label for="inputState">Product price/unit</label>
          <input type="text" class="form-control" name="product_price_per_unit" value="">
        </div>

      </div>
      <br>
      <button type="submit" name="adding_product" class="btn btn-primary">Add item</button>
    </form>
  </div>

  <div class="col-sm-1"></div>
</div>
<br>

  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <table class="table">
  <thead>
    <tr>
      <th scope="col">Product ID</th>
      <th scope="col">Product added by</th>
      <th scope="col">Product Name</th>
      <th scope="col">Product Quantity</th>
      <th scope="col">Product Unit</th>
      <th scope="col">Price/unit</th>
    </tr>
  </thead>
  <tbody>
    {% for i in products %}
    <tr>
      <th scope="row">{{i.company_a_product_id}}</th>
      <td>{{i.product_added_by.first_name}} {{i.product_added_by.last_name}}</td>
      <td>{{i.product_name}}</td>
      <td>{{i.product_quantity}}</td>
      <td>{{i.product_unit}}</td>
      <td>{{i.product_price_per_unit}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
    </div>
    <div class="col-sm-2"></div>
  </div>

</div>



<!-- Footer -->
<footer class="page-footer fixed-bottom font-small bg-dark">

<!-- Copyright -->
<div class="footer-copyright text-center py-3 text-light">© 2020 Copyright:
  <a href="#"> company A</a>
</div>
<!-- Copyright -->

</footer>


  </body>
</html>